spring:
  application:
    name: "ApiGateway"
server:
  port: 9090
  
  
  eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"

cloud:
  gateway:
    routes:
      - id: DEMO1
        uri: lb://DEMO1  # URI for Service 1
        predicates:
          - Path=/test/**
          - Method=GET,POST
          - Header=channel, \d+

      - id: DEMO2
        uri: lb://DEMO2  # URI for Service 2
        predicates:
          - Path=/test2/**

      - id: service3
        uri: http://localhost:8083  # URI for Service 3
        predicates:
          - Path=/service3/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
           